# https://pub.dev/packages/lints
include: package:lints/recommended.yaml

# https://dart.dev/tools/linter-rules
linter:
  rules:
    unnecessary_this: false
    slash_for_doc_comments: false
    unnecessary_new: false
    omit_local_variable_types: false
    library_prefixes: false
    use_function_type_syntax_for_parameters: false
    constant_identifier_names: false
    non_constant_identifier_names: false
#     - camel_case_types

analyzer:
#   exclude:
#     - path/to/excluded/files/**
